### ISSUE TITLE
Default behaviour for non-git folders

### ISSUE THREAD

**Issue by GPMueller** [NOhs/git_info#5]
If someone e.g. downloaded a .zip version of a repo, this should not break the CMake scripts. So the question is: what should the strings be if the directory is not part of a git repo?

As far as I can tell this case is not dealt with?

**Comment by NOhs** [comment]
I guess one alternative would be to supply all variables manually, but this kind of defeats the purpose of this package. It is after all about git. I guess, if someone wants to distribute via zip, they should probably make a check if they are inside a git repository or not and use my package (or don't use it) depending on this. Because anyways they need to also deal with properly including (not including) the header file in their source code.

**Comment by GPMueller** [comment]
I would expect the usage would generally be inside a git repo, but I find the "download as zip" button quite prominent on GitHub.

It may be reasonable to use this as a way to log the exact version (i.e. commit hash) in errors, where "not available" would be a sensible string if the project was downloaded or sent as a zip.

One could (additionally or instead) add a `bool GIT_AVAILABLE`. Usage example:

    if (git_info::GIT_AVAILABLE)
    {
         log(info, "running code version" + git_info::SHA1_PRETTY);
    }

**Comment by NOhs** [comment]
Hm having a floating variable that tells you if others are valid which is accompanied by some documentation telling you to always check if available to make sure what you want to access is actually valid is to "C-ish" for my taste. I don't want to have invalid stuff accessible if I can avoid it. 

Was also thinking about a backup file that would be used if git is not available, but this one would always be one commit behind, because as soon as you commit it, it is outdated.

**Comment by GPMueller** [comment]
How about a default file with "not available" etc. inside?

**Comment by NOhs** [comment]
I added a CMake variable to check if inside a git repository. If not, then one can inject ones own version file instead of using the git-target. This is part of 7afd96444b530543b73b9b00cb8039ca836372aa. If you feel this issue is not resolved by this feel free to comment here.
